using System.Linq;
using Microsoft.CodeAnalysis;
using Aspid.Generators.Helper;
using System.Collections.Generic;
using System.Collections.Immutable;
using UnityFastToolsGenerators.Generators.ProfilerMarkers.Data;
using static Aspid.Generators.Helper.Classes;
using static Aspid.Generators.Helper.Unity.UnityClasses;
using static UnityFastToolsGenerators.Descriptions.General;

namespace UnityFastToolsGenerators.Generators.ProfilerMarkers.Bodies;

public static class ExtensionClassBody
{
    public static void GenerateCode(in SourceProductionContext context, in ImmutableArray<MarkerCall> markerCalls)
    {
        var markerCallTypes = markerCalls
            .GroupBy(markerCall => markerCall.NamedTypeSymbol, SymbolEqualityComparer.Default)
            .Select(group => new MarkerCallType(group.Key!, group.ToImmutableArray()));

        foreach (var markerCallType in markerCallTypes)
            GenerateCode(context, markerCallType);
    }

    private static void GenerateCode(in SourceProductionContext context, in MarkerCallType type)
    {
        var symbol = (INamedTypeSymbol)type.Symbol;
        var typeName = symbol.Name;

        var hasNamespaceName = !symbol.ContainingNamespace.IsGlobalNamespace;
        var namespaceName = hasNamespaceName ? symbol.ContainingNamespace.ToDisplayString() : null;

        var markerCallMembers = type.MarkerCalls
            .GroupBy(markerCall => markerCall.MethodSymbol, SymbolEqualityComparer.Default)
            .Select(grouping => new MarkerCallMember((IMethodSymbol)grouping.Key!, grouping.ToImmutableArray()))
            .ToImmutableArray();

        var className = $"__{typeName}ProfilerMarkerExtensions";
        var typeParameters = symbol.TypeParameters;
        var isGeneric = typeParameters.Length > 0;
        var typeParamList = isGeneric
            ? "<" + string.Join(", ", typeParameters.Select(p => p.Name)) + ">"
            : string.Empty;
        var constraintsClause = BuildConstraintsClause(typeParameters);

        var code = new CodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendLineIf(hasNamespaceName, $"namespace {namespaceName}")
            .BeginBlockIf(hasNamespaceName)
            .AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"internal static class {className}")
            .BeginBlock()
            .AppendProfilerMarkers(symbol, markerCallMembers, typeParamList, constraintsClause, isGeneric)
            .AppendWithoutMessage(symbol, markerCallMembers, typeParamList, constraintsClause, isGeneric)
            .EndBlock()
            .EndBlockIf(hasNamespaceName);

        var hintName = $"{className}.g.cs";
        context.AddSource(hintName, code.GetSourceText());
    }

    private static CodeWriter AppendProfilerMarkers(
        this CodeWriter code,
        INamedTypeSymbol symbol,
        ImmutableArray<MarkerCallMember> markerCallMembers,
        string typeParamList,
        string constraintsClause,
        bool isGeneric)
    {
        if (isGeneric)
        {
            code.AppendLine($"private static class Markers{typeParamList}{constraintsClause}")
                .BeginBlock();
        }

        var fieldVisibility = isGeneric ? "public" : "private";

        foreach (var markerCallMember in markerCallMembers)
        {
            var orderedMarkerCalls = markerCallMember.MarkerCalls
                .OrderBy(markerCall => markerCall.Line);

            foreach (var markerCall in orderedMarkerCalls)
            {
                var markerValueExpression = BuildMarkerValueExpression(symbol, markerCall);
                code.AppendMultiline(
                    $"""
                    [{ProfilerMarkerGeneratedCode}]
                    {fieldVisibility} static readonly {ProfilerMarker} {markerCall.MarkerName} = new({markerValueExpression});

                    """);
            }
        }

        if (isGeneric)
            code.EndBlock().AppendLine();

        return code;
    }

    private static CodeWriter AppendWithoutMessage(
        this CodeWriter code,
        INamedTypeSymbol symbol,
        ImmutableArray<MarkerCallMember> markerCallMembers,
        string typeParamList,
        string constraintsClause,
        bool isGeneric)
    {
        code.AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"public static {ProfilerMarker}.AutoScope Marker{typeParamList}(this {symbol.ToDisplayStringGlobal()} _, [{CallerLineNumberAttribute}] int line = -1){constraintsClause}")
            .BeginBlock();

        var prefix = isGeneric ? $"Markers{typeParamList}." : string.Empty;
        foreach (var markerCall in markerCallMembers.SelectMany(member => member.MarkerCalls))
            code.AppendLine($"if (line is {markerCall.Line}) return {prefix}{markerCall.MarkerName}.Auto();");

        code.AppendLine()
            .AppendLine($"throw new {Exception}();")
            .EndBlock();

        return code;
    }

    private static string BuildMarkerValueExpression(INamedTypeSymbol symbol, MarkerCall markerCall)
    {
        if (symbol.TypeParameters.Length is 0)
            return $"\"{symbol.Name}.{markerCall.Label} ({markerCall.Line})\"";

        var typeArgs = string.Join(", ", symbol.TypeParameters.Select(p => $"{{typeof({p.Name}).Name}}"));
        return $"$\"{symbol.Name}<{typeArgs}>.{markerCall.Label} ({markerCall.Line})\"";
    }

    private static string BuildConstraintsClause(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.Length is 0) return string.Empty;

        var clauses = new List<string>();
        foreach (var tp in typeParameters)
        {
            var constraints = new List<string>();

            if (tp.HasReferenceTypeConstraint) constraints.Add("class");
            else if (tp.HasUnmanagedTypeConstraint) constraints.Add("unmanaged");
            else if (tp.HasValueTypeConstraint) constraints.Add("struct");

            if (tp.HasNotNullConstraint) constraints.Add("notnull");

            foreach (var ct in tp.ConstraintTypes)
                constraints.Add(ct.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

            if (tp.HasConstructorConstraint) constraints.Add("new()");

            if (constraints.Count > 0)
                clauses.Add($"where {tp.Name} : {string.Join(", ", constraints)}");
        }

        return clauses.Count is 0 ? string.Empty : " " + string.Join(" ", clauses);
    }
}
