using System.Text;
using Microsoft.CodeAnalysis;
using Aspid.Generators.Helper;
using Aspid.FastTools.Generators.IdStruct.Data;

namespace Aspid.FastTools.Generators.IdStruct.Bodies;

public static class IdStructBody
{
    public static void GenerateCode(in SourceProductionContext context, in IdStructData data)
    {
        var hasNamespace = data.Namespace != null;
        var nestedDepth = data.ContainingTypes.Length;

        var code = new CodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendLineIf(hasNamespace, $"namespace {data.Namespace}")
            .BeginBlockIf(hasNamespace);

        var nestedNames = new StringBuilder();
        foreach (var containing in data.ContainingTypes)
        {
            code.AppendLine($"partial {containing.Keyword} {containing.Name}")
                .BeginBlock();
            nestedNames.Append(containing.Name).Append('.');
        }

        code.AppendLine($"partial struct {data.StructName}")
            .BeginBlock()
            .AppendLine("#if UNITY_EDITOR")
            .AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]")
            .AppendLine("[global::UnityEngine.SerializeField] private string __stringId;")
            .AppendLine("#endif")
            .AppendLine("[global::UnityEngine.SerializeField] private int _id;")
            .AppendLine("public int Id => _id;")
            .EndBlock();

        for (var i = 0; i < nestedDepth; i++)
            code.EndBlock();

        code.EndBlockIf(hasNamespace);

        var hintName = hasNamespace
            ? $"{data.Namespace}.{nestedNames}{data.StructName}.IId.g.cs"
            : $"{nestedNames}{data.StructName}.IId.g.cs";

        context.AddSource(hintName, code.GetSourceText());
    }
}
