// Generated by scripts/docfx-postprocess.mjs from toc.yml. Do not edit.
export default { api: [
  {
    "type": "category",
    "key": "Aspid.FastTools",
    "label": "Aspid.FastTools",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.StringExtensions",
            "label": "StringExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.TypeExtensions",
            "label": "TypeExtensions (FastTools)"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Editors",
    "label": "Aspid.FastTools.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Editors.EditorExtensions",
            "label": "EditorExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Editors.SerializePropertyExtensions",
            "label": "SerializePropertyExtensions"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Enums",
    "label": "Aspid.FastTools.Enums",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Enums"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Enums.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Enums.EnumValues-2",
            "label": "EnumValues<TEnum, TValue>"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Enums.EnumValues-1",
            "label": "EnumValues<TValue>"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Enums.Structs",
        "label": "Structs",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Enums.EnumValuesEnumerator-2",
            "label": "EnumValuesEnumerator<TKey, TValue>"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Ids",
    "label": "Aspid.FastTools.Ids",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Ids"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Ids.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.IdRegistry",
            "label": "IdRegistry"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.IdRegistry-1",
            "label": "IdRegistry<T>"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.UniqueIdAttribute",
            "label": "UniqueIdAttribute"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Ids.Interfaces",
        "label": "Interfaces",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.IId",
            "label": "IId"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Ids.Editors",
    "label": "Aspid.FastTools.Ids.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Ids.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Ids.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.Editors.IdField",
            "label": "IdField"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.Editors.IdField.UxmlSerializedData",
            "label": "IdField.UxmlSerializedData"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.Editors.InspectorIdField",
            "label": "InspectorIdField"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Ids.Editors.InspectorIdField.UxmlSerializedData",
            "label": "InspectorIdField.UxmlSerializedData"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.SerializeReferences.Editors",
    "label": "Aspid.FastTools.SerializeReferences.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.SerializeReferences.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.SerializeReferences.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.SerializeReferences.Editors.SerializeReferenceEditorGUI",
            "label": "SerializeReferenceEditorGUI"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.SerializeReferences.Editors.SerializeReferenceIMGUIList",
            "label": "SerializeReferenceIMGUIList"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Types",
    "label": "Aspid.FastTools.Types",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Types"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.SerializableType",
            "label": "SerializableType"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.SerializableType-1",
            "label": "SerializableType<T>"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.TypeSelectorAttribute",
            "label": "TypeSelectorAttribute"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.TypeSelectorDisplayAttribute",
            "label": "TypeSelectorDisplayAttribute"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Structs",
        "label": "Structs",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.ComponentTypeSelector",
            "label": "ComponentTypeSelector"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Interfaces",
        "label": "Interfaces",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.ISerializableType",
            "label": "ISerializableType"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Enums",
        "label": "Enums",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.TypeAllow",
            "label": "TypeAllow"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Types.Editors",
    "label": "Aspid.FastTools.Types.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Types.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.InspectorTypeField",
            "label": "InspectorTypeField"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.InspectorTypeField.UxmlSerializedData",
            "label": "InspectorTypeField.UxmlSerializedData"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeExtensions",
            "label": "TypeExtensions (Editors)"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeField",
            "label": "TypeField"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeField.UxmlSerializedData",
            "label": "TypeField.UxmlSerializedData"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeSelectorWindow",
            "label": "TypeSelectorWindow"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Editors.Structs",
        "label": "Structs",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeSelectorFilter",
            "label": "TypeSelectorFilter"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Editors.Delegates",
        "label": "Delegates",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.GenericArgumentFilter",
            "label": "GenericArgumentFilter"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.UIElements",
    "label": "Aspid.FastTools.UIElements",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.UIElements"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.UIElements.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseBoolFieldExtensions",
            "label": "BaseBoolFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensions",
            "label": "BaseFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelAnimationCurve",
            "label": "BaseFieldExtensionsSetLabelAnimationCurve"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelBounds",
            "label": "BaseFieldExtensionsSetLabelBounds"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelBoundsInt",
            "label": "BaseFieldExtensionsSetLabelBoundsInt"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelByte",
            "label": "BaseFieldExtensionsSetLabelByte"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelChar",
            "label": "BaseFieldExtensionsSetLabelChar"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelColor",
            "label": "BaseFieldExtensionsSetLabelColor"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelColor32",
            "label": "BaseFieldExtensionsSetLabelColor32"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelDecimal",
            "label": "BaseFieldExtensionsSetLabelDecimal"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelDouble",
            "label": "BaseFieldExtensionsSetLabelDouble"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelEnum",
            "label": "BaseFieldExtensionsSetLabelEnum"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelFloat",
            "label": "BaseFieldExtensionsSetLabelFloat"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelGradient",
            "label": "BaseFieldExtensionsSetLabelGradient"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelHash128",
            "label": "BaseFieldExtensionsSetLabelHash128"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelInt",
            "label": "BaseFieldExtensionsSetLabelInt"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelLong",
            "label": "BaseFieldExtensionsSetLabelLong"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelObject",
            "label": "BaseFieldExtensionsSetLabelObject"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelQuaternion",
            "label": "BaseFieldExtensionsSetLabelQuaternion"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelRect",
            "label": "BaseFieldExtensionsSetLabelRect"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelSbyte",
            "label": "BaseFieldExtensionsSetLabelSbyte"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelShort",
            "label": "BaseFieldExtensionsSetLabelShort"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelString",
            "label": "BaseFieldExtensionsSetLabelString"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelUint",
            "label": "BaseFieldExtensionsSetLabelUint"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelUlong",
            "label": "BaseFieldExtensionsSetLabelUlong"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelUshort",
            "label": "BaseFieldExtensionsSetLabelUshort"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelVector2",
            "label": "BaseFieldExtensionsSetLabelVector2"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelVector2Int",
            "label": "BaseFieldExtensionsSetLabelVector2Int"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelVector3",
            "label": "BaseFieldExtensionsSetLabelVector3"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelVector3Int",
            "label": "BaseFieldExtensionsSetLabelVector3Int"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensionsSetLabelVector4",
            "label": "BaseFieldExtensionsSetLabelVector4"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseListViewExtensions",
            "label": "BaseListViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseTreeViewExtensions",
            "label": "BaseTreeViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseVerticalCollectionViewExtensions",
            "label": "BaseVerticalCollectionViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ButtonExtensions",
            "label": "ButtonExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.EnumFieldExtensions",
            "label": "EnumFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.FocusableExtensions",
            "label": "FocusableExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.FoldoutExtensions",
            "label": "FoldoutExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.HelpBoxExtensions",
            "label": "HelpBoxExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ICustomStyleExtensions",
            "label": "ICustomStyleExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.IMGUIContainerExtensions",
            "label": "IMGUIContainerExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.IMixedValueSupportExtensions",
            "label": "IMixedValueSupportExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.INotifyValueChangedExtensions",
            "label": "INotifyValueChangedExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.IStyleExtensions",
            "label": "IStyleExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ITextEditionExtensions",
            "label": "ITextEditionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ITextSelectionExtensions",
            "label": "ITextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ImageExtensions",
            "label": "ImageExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ListViewExtensions",
            "label": "ListViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ManipulatorExtensions",
            "label": "ManipulatorExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.MultiColumnListViewExtensions",
            "label": "MultiColumnListViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.MultiColumnTreeViewExtensions",
            "label": "MultiColumnTreeViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ProgressBarExtensions",
            "label": "ProgressBarExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.SliderExtensions",
            "label": "SliderExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextElementExtensions",
            "label": "TextElementExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TreeViewExtensions",
            "label": "TreeViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.VisualElementExtensions",
            "label": "VisualElementExtensions (UIElements)"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.UIElements.Editors",
    "label": "Aspid.FastTools.UIElements.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.UIElements.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.UIElements.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.EnumFlagsFieldExtensions",
            "label": "EnumFlagsFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.IBindableExtensions",
            "label": "IBindableExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.PropertyFieldExtensions",
            "label": "PropertyFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.VisualElementExtensions",
            "label": "VisualElementExtensions (Editors)"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "ProfilerMarkerExtensionsForGenerator",
    "label": "ProfilerMarkerExtensionsForGenerator",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "ProfilerMarkerExtensionsForGenerator"
    },
    "items": []
  }
] };
