// Generated by scripts/docfx-postprocess.mjs from toc.yml. Do not edit.
export default { api: [
  {
    "type": "category",
    "key": "Aspid.FastTools.Editors",
    "label": "Aspid.FastTools.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Editors.EditorExtensions",
            "label": "EditorExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Editors.SerializePropertyExtensions",
            "label": "SerializePropertyExtensions"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Enums",
    "label": "Aspid.FastTools.Enums",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Enums"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Enums.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Enums.EnumValues-2",
            "label": "EnumValues<TEnum, TValue>"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Enums.EnumValues-1",
            "label": "EnumValues<TValue>"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Enums.Structs",
        "label": "Structs",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Enums.EnumValuesEnumerator-2",
            "label": "EnumValuesEnumerator<TKey, TValue>"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.SerializeReferences.Editors",
    "label": "Aspid.FastTools.SerializeReferences.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.SerializeReferences.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.SerializeReferences.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.SerializeReferences.Editors.SerializeReferenceEditorGUI",
            "label": "SerializeReferenceEditorGUI"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.SerializeReferences.Editors.SerializeReferenceIMGUIList",
            "label": "SerializeReferenceIMGUIList"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Types",
    "label": "Aspid.FastTools.Types",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Types"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.SerializableMonoScript",
            "label": "SerializableMonoScript"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.SerializableMonoScript-1",
            "label": "SerializableMonoScript<T>"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.SerializableType",
            "label": "SerializableType"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.SerializableType-1",
            "label": "SerializableType<T>"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.SerializableTypeBase",
            "label": "SerializableTypeBase"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.TypeSelectorAttribute",
            "label": "TypeSelectorAttribute"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.TypeSelectorDisplayAttribute",
            "label": "TypeSelectorDisplayAttribute"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Structs",
        "label": "Structs",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.ComponentTypeSelector",
            "label": "ComponentTypeSelector"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Interfaces",
        "label": "Interfaces",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.ISerializableType",
            "label": "ISerializableType"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Enums",
        "label": "Enums",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.TypeAllow",
            "label": "TypeAllow"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.Types.Editors",
    "label": "Aspid.FastTools.Types.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.Types.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.InspectorTypeField",
            "label": "InspectorTypeField"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.InspectorTypeField.UxmlSerializedData",
            "label": "InspectorTypeField.UxmlSerializedData"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeExtensions",
            "label": "TypeExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeField",
            "label": "TypeField"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeField.UxmlSerializedData",
            "label": "TypeField.UxmlSerializedData"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeSelectorWindow",
            "label": "TypeSelectorWindow"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Editors.Structs",
        "label": "Structs",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.TypeSelectorFilter",
            "label": "TypeSelectorFilter"
          }
        ]
      },
      {
        "type": "category",
        "key": "Aspid.FastTools.Types.Editors.Delegates",
        "label": "Delegates",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.Types.Editors.GenericArgumentFilter",
            "label": "GenericArgumentFilter"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.UIElements",
    "label": "Aspid.FastTools.UIElements",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.UIElements"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.UIElements.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.AbstractProgressBarExtensions",
            "label": "AbstractProgressBarExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseBoolFieldExtensions",
            "label": "BaseBoolFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldAnimationCurveExtensions",
            "label": "BaseFieldAnimationCurveExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldBoundsExtensions",
            "label": "BaseFieldBoundsExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldBoundsIntExtensions",
            "label": "BaseFieldBoundsIntExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldByteExtensions",
            "label": "BaseFieldByteExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldCharExtensions",
            "label": "BaseFieldCharExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldColor32Extensions",
            "label": "BaseFieldColor32Extensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldColorExtensions",
            "label": "BaseFieldColorExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldDecimalExtensions",
            "label": "BaseFieldDecimalExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldDoubleExtensions",
            "label": "BaseFieldDoubleExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldEnumExtensions",
            "label": "BaseFieldEnumExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldExtensions",
            "label": "BaseFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldFloatExtensions",
            "label": "BaseFieldFloatExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldGradientExtensions",
            "label": "BaseFieldGradientExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldHash128Extensions",
            "label": "BaseFieldHash128Extensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldIntExtensions",
            "label": "BaseFieldIntExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldLongExtensions",
            "label": "BaseFieldLongExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldObjectExtensions",
            "label": "BaseFieldObjectExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldQuaternionExtensions",
            "label": "BaseFieldQuaternionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldRectExtensions",
            "label": "BaseFieldRectExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldSbyteExtensions",
            "label": "BaseFieldSbyteExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldShortExtensions",
            "label": "BaseFieldShortExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldStringExtensions",
            "label": "BaseFieldStringExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldUintExtensions",
            "label": "BaseFieldUintExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldUlongExtensions",
            "label": "BaseFieldUlongExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldUshortExtensions",
            "label": "BaseFieldUshortExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldVector2Extensions",
            "label": "BaseFieldVector2Extensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldVector2IntExtensions",
            "label": "BaseFieldVector2IntExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldVector3Extensions",
            "label": "BaseFieldVector3Extensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldVector3IntExtensions",
            "label": "BaseFieldVector3IntExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseFieldVector4Extensions",
            "label": "BaseFieldVector4Extensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseListViewExtensions",
            "label": "BaseListViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseTreeViewExtensions",
            "label": "BaseTreeViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.BaseVerticalCollectionViewExtensions",
            "label": "BaseVerticalCollectionViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ButtonExtensions",
            "label": "ButtonExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.EnumFieldExtensions",
            "label": "EnumFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.FocusableExtensions",
            "label": "FocusableExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.FoldoutExtensions",
            "label": "FoldoutExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.HelpBoxExtensions",
            "label": "HelpBoxExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ICustomStyleExtensions",
            "label": "ICustomStyleExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.IMGUIContainerExtensions",
            "label": "IMGUIContainerExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.IMixedValueSupportExtensions",
            "label": "IMixedValueSupportExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.INotifyValueChangedExtensions",
            "label": "INotifyValueChangedExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.IStyleExtensions",
            "label": "IStyleExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ITextEditionExtensions",
            "label": "ITextEditionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ITextSelectionExtensions",
            "label": "ITextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ImageExtensions",
            "label": "ImageExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ListViewExtensions",
            "label": "ListViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.ManipulatorExtensions",
            "label": "ManipulatorExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.MultiColumnListViewExtensions",
            "label": "MultiColumnListViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.MultiColumnTreeViewExtensions",
            "label": "MultiColumnTreeViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.SliderExtensions",
            "label": "SliderExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.SliderIntExtensions",
            "label": "SliderIntExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextElementExtensions",
            "label": "TextElementExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldDoubleExtensions",
            "label": "TextInputBaseFieldDoubleExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldDoubleTextSelectionExtensions",
            "label": "TextInputBaseFieldDoubleTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldExtensions",
            "label": "TextInputBaseFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldFloatExtensions",
            "label": "TextInputBaseFieldFloatExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldFloatTextSelectionExtensions",
            "label": "TextInputBaseFieldFloatTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldHash128Extensions",
            "label": "TextInputBaseFieldHash128Extensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldHash128TextSelectionExtensions",
            "label": "TextInputBaseFieldHash128TextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldIntExtensions",
            "label": "TextInputBaseFieldIntExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldIntTextSelectionExtensions",
            "label": "TextInputBaseFieldIntTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldLongExtensions",
            "label": "TextInputBaseFieldLongExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldLongTextSelectionExtensions",
            "label": "TextInputBaseFieldLongTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldStringExtensions",
            "label": "TextInputBaseFieldStringExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldStringTextSelectionExtensions",
            "label": "TextInputBaseFieldStringTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldTextSelectionExtensions",
            "label": "TextInputBaseFieldTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldUintExtensions",
            "label": "TextInputBaseFieldUintExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldUintTextSelectionExtensions",
            "label": "TextInputBaseFieldUintTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldUlongExtensions",
            "label": "TextInputBaseFieldUlongExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TextInputBaseFieldUlongTextSelectionExtensions",
            "label": "TextInputBaseFieldUlongTextSelectionExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.TreeViewExtensions",
            "label": "TreeViewExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.VisualElementExtensions",
            "label": "VisualElementExtensions (UIElements)"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "Aspid.FastTools.UIElements.Editors",
    "label": "Aspid.FastTools.UIElements.Editors",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "Aspid.FastTools.UIElements.Editors"
    },
    "items": [
      {
        "type": "category",
        "key": "Aspid.FastTools.UIElements.Editors.Classes",
        "label": "Classes",
        "collapsed": true,
        "items": [
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.EnumFlagsFieldExtensions",
            "label": "EnumFlagsFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.IBindableExtensions",
            "label": "IBindableExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.PropertyFieldExtensions",
            "label": "PropertyFieldExtensions"
          },
          {
            "type": "doc",
            "id": "Aspid.FastTools.UIElements.Editors.VisualElementExtensions",
            "label": "VisualElementExtensions (Editors)"
          }
        ]
      }
    ]
  },
  {
    "type": "category",
    "key": "ProfilerMarkerExtensionsForGenerator",
    "label": "ProfilerMarkerExtensionsForGenerator",
    "collapsed": true,
    "link": {
      "type": "doc",
      "id": "ProfilerMarkerExtensionsForGenerator"
    },
    "items": []
  }
] };
