using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Aspid.Generators.Helper;
using System.Collections.Generic;
using System.Collections.Immutable;
using Aspid.FastTools.Generators.ProfilerMarkers.Data;
using static Aspid.Generators.Helper.Classes;
using static Aspid.FastTools.Descriptions.General;
using static Aspid.Generators.Helper.Unity.UnityClasses;

namespace Aspid.FastTools.Generators.ProfilerMarkers.Bodies;

internal static class ExtensionClassBody
{
    public static void GenerateCode(in SourceProductionContext context, in ImmutableArray<MarkerCall> markerCalls)
    {
        // Ordinal order keeps the de-duplicated class and file names stable between runs.
        var typeGroups = markerCalls
            .GroupBy(static call => call.Type.TypeKey, StringComparer.Ordinal)
            .OrderBy(static group => group.Key, StringComparer.Ordinal);

        var classNames = new HashSet<string>(StringComparer.Ordinal);
        var hintNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var typeGroup in typeGroups)
        {
            var type = typeGroup.First().Type;

            // Outer.Inner and Outer_Inner both flatten to __Outer_Inner…; the second one gets a suffix.
            var className = MakeUnique(type.ClassName, name => classNames.Add((type.Namespace ?? string.Empty) + "." + name));

            // Hint names compare case-insensitively and may not contain '@'.
            var hintPrefix = type.Namespace is null ? string.Empty : type.Namespace.Replace("@", string.Empty) + ".";
            var hintName = MakeUnique(hintPrefix + className, name => hintNames.Add(name));

            // Calls sharing a line share the first one's marker: [CallerLineNumber] cannot tell them apart.
            var calls = typeGroup
                .OrderBy(static call => call.Line)
                .ThenBy(static call => call.FilePath, StringComparer.Ordinal)
                .ThenBy(static call => call.Position)
                .GroupBy(static call => call.Line)
                .Select(static line => line.First())
                .ToImmutableArray();

            context.AddSource(hintName + ".g.cs", GenerateForType(type, className, calls));
        }
    }

    private static string MakeUnique(string name, Func<string, bool> tryAdd)
    {
        if (tryAdd(name)) return name;

        for (var i = 2; ; i++)
        {
            var candidate = $"{name}_{i}";
            if (tryAdd(candidate)) return candidate;
        }
    }

    private static Microsoft.CodeAnalysis.Text.SourceText GenerateForType(TypeData type, string className, ImmutableArray<MarkerCall> calls)
    {
        var hasNamespace = type.Namespace is not null;
        var names = new GeneratedNames(type);

        // A generic class gets one marker per closed type. A generic struct keeps one literal name:
        // it may be a Burst job, and Burst cannot run the typeof(T) of a per-type label.
        var isPerClosedType = type.Arity > 0 && !type.IsValueType;

        var code = new CodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendLineIf(hasNamespace, $"namespace {type.Namespace}")
            .BeginBlockIf(hasNamespace)
            .AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"internal static class {className}")
            .BeginBlock()
            .AppendProfilerMarkers(type, names, calls, isPerClosedType)
            .AppendMarker(type, names, calls, isPerClosedType)
            .EndBlock()
            .EndBlockIf(hasNamespace);

        return code.GetSourceText();
    }

    private static CodeWriter AppendProfilerMarkers(
        this CodeWriter code,
        TypeData type,
        GeneratedNames names,
        ImmutableArray<MarkerCall> calls,
        bool isPerClosedType)
    {
        // Marker() reads the fields only under ENABLE_PROFILER, so without it they would still
        // create every marker in the static constructor for nothing.
        code.AppendLine("#if ENABLE_PROFILER");

        if (isPerClosedType)
        {
            code.AppendLine($"private static class {names.Markers}{type.TypeParamList}{type.ConstraintsClause}")
                .BeginBlock();
        }

        var fieldVisibility = isPerClosedType ? "public" : "private";

        for (var i = 0; i < calls.Length; i++)
        {
            if (i > 0) code.AppendLine();

            var call = calls[i];
            code.AppendLine($"[{ProfilerMarkerGeneratedCode}]")
                .AppendLine($"{fieldVisibility} static readonly {ProfilerMarker} {call.FieldName} = new({BuildMarkerValueExpression(type, names, call, isPerClosedType)});");
        }

        if (isPerClosedType)
        {
            code.EndBlock()
                .AppendLine()
                .AppendTypeNameHelper(names);
        }

        return code.AppendLine("#endif")
            .AppendLine();
    }

    // Formats typeof(T) the way C# writes it, so List<int> and List<string> get different marker names.
    private static CodeWriter AppendTypeNameHelper(this CodeWriter code, GeneratedNames names) =>
        code.AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"private static string {names.TypeName}(global::System.Type type)")
            .BeginBlock()
            .AppendLine("var name = type.Name;")
            .AppendLine("var tick = name.IndexOf('`');")
            .AppendLine("if (tick < 0) return name;")
            .AppendLine()
            .AppendLine("var arguments = type.GetGenericArguments();")
            .AppendLine("var names = new string[arguments.Length];")
            .AppendLine("for (var i = 0; i < arguments.Length; i++)")
            .AppendLine($"    names[i] = {names.TypeName}(arguments[i]);")
            .AppendLine()
            .AppendLine("return name.Substring(0, tick) + \"<\" + string.Join(\", \", names) + \">\";")
            .EndBlock();

    private static CodeWriter AppendMarker(
        this CodeWriter code,
        TypeData type,
        GeneratedNames names,
        ImmutableArray<MarkerCall> calls,
        bool isPerClosedType)
    {
        code.AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"public static {ProfilerMarker}.AutoScope Marker{type.TypeParamList}(this {type.FullyQualifiedDisplay} {names.Instance}, [{CallerLineNumberAttribute}] int {names.Line} = -1){type.ConstraintsClause}")
            .BeginBlock()
            .AppendLine("#if ENABLE_PROFILER")
            .AppendLine($"switch ({names.Line})")
            .BeginBlock();

        var prefix = isPerClosedType ? $"{names.Markers}{type.TypeParamList}." : string.Empty;
        foreach (var call in calls)
            code.AppendLine($"case {call.Line}: return {prefix}{call.FieldName}.Auto();");

        code.EndBlock()
            .AppendLine("#endif")
            .AppendLine("return default;")
            .EndBlock();

        return code;
    }

    private static string BuildMarkerValueExpression(TypeData type, GeneratedNames names, MarkerCall call, bool isPerClosedType)
    {
        // call.Label may originate from a user-supplied .WithName("...") literal and can contain
        // quotes, backslashes or braces. Every literal fragment is emitted through ToLiteral so the
        // result is always valid C# — the raw label is never interpolated verbatim into the source.
        var typeParameters = type.OwnTypeParameters.Length > 0
            ? type.OwnTypeParameters.Split(',')
            : System.Array.Empty<string>();

        if (typeParameters.Length is 0)
            return ToLiteral($"{type.TypeName}.{call.Label} ({call.Line})");

        if (!isPerClosedType)
            return ToLiteral($"{type.TypeName}<{string.Join(", ", typeParameters)}>.{call.Label} ({call.Line})");

        // The label names each closed type, so build it from escaped literals and TypeName(typeof(T))
        // calls instead of one interpolated string, which would break on braces inside the label.
        var typeofExpressions = string.Join(
            " + \", \" + ",
            typeParameters.Select(p => $"{names.TypeName}(typeof({ProfilerMarkersGenerator.EscapeIdentifier(p)}))"));

        var prefix = ToLiteral($"{type.TypeName}<");
        var suffix = ToLiteral($">.{call.Label} ({call.Line})");
        return $"{prefix} + {typeofExpressions} + {suffix}";
    }

    // Renders an arbitrary string as a valid C# double-quoted string literal (quotes included),
    // escaping quotes, backslashes, control characters, line separators and surrogates so
    // user-supplied .WithName(...) text can never produce malformed generated source.
    private static string ToLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var c in value)
        {
            switch (c)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\0': builder.Append("\\0"); break;
                case '\a': builder.Append("\\a"); break;
                case '\b': builder.Append("\\b"); break;
                case '\f': builder.Append("\\f"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case '\v': builder.Append("\\v"); break;
                default:
                    // U+0085, U+2028 and U+2029 end a line inside a C# literal; a surrogate written
                    // on its own would not survive the UTF-8 source text.
                    if (c < ' ' || c is >= '\u007F' and <= '\u009F' || c is (char)0x2028 or (char)0x2029 || char.IsSurrogate(c))
                        builder.Append("\\u").Append(((int)c).ToString("x4"));
                    else
                        builder.Append(c);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    // Identifiers the generated code declares next to the user's type parameters, which may reuse any name.
    private readonly struct GeneratedNames
    {
        public readonly string Instance;
        public readonly string Line;
        public readonly string Markers;
        public readonly string TypeName;

        public GeneratedNames(TypeData type)
        {
            var taken = new HashSet<string>(
                type.TypeParamList.Trim('<', '>').Split(',').Select(static p => p.Trim().TrimStart('@')),
                StringComparer.Ordinal);

            Instance = Unique("__instance", taken);
            Line = Unique("__line", taken);
            Markers = Unique("__Markers", taken);
            TypeName = Unique("__TypeName", taken);
        }

        private static string Unique(string name, HashSet<string> taken)
        {
            while (taken.Contains(name))
                name += "_";

            return name;
        }
    }
}
