using System.Linq;
using Microsoft.CodeAnalysis;
using Aspid.Generators.Helper;
using System.Collections.Generic;
using System.Collections.Immutable;
using Aspid.FastTools.Generators.ProfilerMarkers.Data;
using static Aspid.Generators.Helper.Classes;
using static Aspid.FastTools.Descriptions.General;
using static Aspid.Generators.Helper.Unity.UnityClasses;

namespace Aspid.FastTools.Generators.ProfilerMarkers.Bodies;

internal static class ExtensionClassBody
{
    public static void GenerateCode(in SourceProductionContext context, in ImmutableArray<MarkerCall> markerCalls)
    {
        var typeGroups = markerCalls.GroupBy(call => call.Type.TypeKey);

        foreach (var typeGroup in typeGroups)
            GenerateForType(context, typeGroup);
    }

    private static void GenerateForType(SourceProductionContext context, IGrouping<string, MarkerCall> typeGroup)
    {
        var calls = typeGroup.ToImmutableArray();
        var type = calls[0].Type;

        var memberGroups = calls
            .GroupBy(call => call.MethodKey)
            .Select(g => g.OrderBy(c => c.Line).ToImmutableArray())
            .ToImmutableArray();

        var renamedByMember = AssignUniqueFieldNames(memberGroups);

        var hasNamespace = !string.IsNullOrEmpty(type.Namespace);
        var aritySuffix = type.Arity > 0 ? $"_{type.Arity}" : string.Empty;
        var containingPart = type.ContainingTypeChain.Replace('.', '_');
        var className = $"__{containingPart}{type.TypeName}{aritySuffix}ProfilerMarkerExtensions";
        var isGeneric = type.TypeParamList.Length > 0;

        var code = new CodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendLineIf(hasNamespace, $"namespace {type.Namespace}")
            .BeginBlockIf(hasNamespace)
            .AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"internal static class {className}")
            .BeginBlock()
            .AppendProfilerMarkers(type, renamedByMember, isGeneric)
            .AppendWithoutMessage(type, renamedByMember, isGeneric)
            .EndBlock()
            .EndBlockIf(hasNamespace);

        var hintNamespacePart = hasNamespace ? type.Namespace + "." : string.Empty;
        var hintName = $"{hintNamespacePart}{type.ContainingTypeChain}{type.TypeName}{aritySuffix}ProfilerMarkerExtensions.g.cs";
        context.AddSource(hintName, code.GetSourceText());
    }

    private static List<ImmutableArray<RenamedCall>> AssignUniqueFieldNames(ImmutableArray<ImmutableArray<MarkerCall>> memberGroups)
    {
        var seen = new Dictionary<string, int>();
        var result = new List<ImmutableArray<RenamedCall>>(memberGroups.Length);

        foreach (var member in memberGroups)
        {
            var renamed = ImmutableArray.CreateBuilder<RenamedCall>(member.Length);
            foreach (var call in member)
            {
                seen.TryGetValue(call.MarkerName, out var count);
                seen[call.MarkerName] = count + 1;
                var fieldName = count == 0 ? call.MarkerName : $"{call.MarkerName}_{count + 1}";
                renamed.Add(new RenamedCall(call, fieldName));
            }
            result.Add(renamed.MoveToImmutable());
        }

        return result;
    }

    private static CodeWriter AppendProfilerMarkers(
        this CodeWriter code,
        TypeData type,
        List<ImmutableArray<RenamedCall>> members,
        bool isGeneric)
    {
        if (isGeneric)
        {
            code.AppendLine($"private static class Markers{type.TypeParamList}{type.ConstraintsClause}")
                .BeginBlock();
        }

        var fieldVisibility = isGeneric ? "public" : "private";

        foreach (var member in members)
        {
            foreach (var renamed in member)
            {
                var markerValueExpression = BuildMarkerValueExpression(type, renamed.Call);
                code.AppendMultiline(
                    $"""
                    [{ProfilerMarkerGeneratedCode}]
                    {fieldVisibility} static readonly {ProfilerMarker} {renamed.FieldName} = new({markerValueExpression});

                    """);
            }
        }

        if (isGeneric)
            code.EndBlock().AppendLine();

        return code;
    }

    private static CodeWriter AppendWithoutMessage(
        this CodeWriter code,
        TypeData type,
        List<ImmutableArray<RenamedCall>> members,
        bool isGeneric)
    {
        code.AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"public static {ProfilerMarker}.AutoScope Marker{type.TypeParamList}(this {type.FullyQualifiedDisplay} _, [{CallerLineNumberAttribute}] int line = -1){type.ConstraintsClause}")
            .BeginBlock();

        var prefix = isGeneric ? $"Markers{type.TypeParamList}." : string.Empty;
        foreach (var member in members)
        {
            foreach (var renamed in member)
                code.AppendLine($"if (line is {renamed.Call.Line}) return {prefix}{renamed.FieldName}.Auto();");
        }

        code.AppendLine()
            .AppendLine($"throw new {Exception}();")
            .EndBlock();

        return code;
    }

    private static string BuildMarkerValueExpression(TypeData type, MarkerCall call)
    {
        if (type.Arity == 0)
            return $"\"{type.TypeName}.{call.Label} ({call.Line})\"";

        var typeArgs = ExtractTypeParamNames(type.TypeParamList);
        var interpolations = string.Join(", ", typeArgs.Select(p => $"{{typeof({p}).Name}}"));
        return $"$\"{type.TypeName}<{interpolations}>.{call.Label} ({call.Line})\"";
    }

    private static IEnumerable<string> ExtractTypeParamNames(string typeParamList)
    {
        if (string.IsNullOrEmpty(typeParamList)) yield break;

        var inner = typeParamList.Substring(1, typeParamList.Length - 2);
        foreach (var part in inner.Split(','))
            yield return part.Trim();
    }

    private readonly struct RenamedCall
    {
        public readonly MarkerCall Call;
        public readonly string FieldName;

        public RenamedCall(MarkerCall call, string fieldName)
        {
            Call = call;
            FieldName = fieldName;
        }
    }
}
