using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Aspid.Generators.Helper;
using System.Collections.Generic;
using System.Collections.Immutable;
using Aspid.FastTools.Generators.ProfilerMarkers.Data;
using static Aspid.Generators.Helper.Classes;
using static Aspid.FastTools.Descriptions.General;
using static Aspid.Generators.Helper.Unity.UnityClasses;

namespace Aspid.FastTools.Generators.ProfilerMarkers.Bodies;

internal static class ExtensionClassBody
{
    public static void GenerateCode(in SourceProductionContext context, in ImmutableArray<MarkerCall> markerCalls)
    {
        var typeGroups = markerCalls.GroupBy(call => call.Type.TypeKey);

        foreach (var typeGroup in typeGroups)
            GenerateForType(context, typeGroup);
    }

    private static void GenerateForType(SourceProductionContext context, IGrouping<string, MarkerCall> typeGroup)
    {
        var calls = typeGroup.ToImmutableArray();
        var type = calls[0].Type;

        var memberGroups = calls
            .GroupBy(call => call.MethodKey)
            .Select(g => g.OrderBy(c => c.Line).ToImmutableArray())
            .ToImmutableArray();

        var renamedByMember = AssignUniqueFieldNames(memberGroups);

        var hasNamespace = !string.IsNullOrEmpty(type.Namespace);
        var aritySuffix = type.Arity > 0 ? $"_{type.Arity}" : string.Empty;
        var containingPart = type.ContainingTypeChain.Replace('.', '_');
        var className = $"__{containingPart}{type.TypeName}{aritySuffix}ProfilerMarkerExtensions";
        var isGeneric = type.TypeParamList.Length > 0;

        var code = new CodeWriter()
            .AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendLineIf(hasNamespace, $"namespace {type.Namespace}")
            .BeginBlockIf(hasNamespace)
            .AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"internal static class {className}")
            .BeginBlock()
            .AppendProfilerMarkers(type, renamedByMember, isGeneric)
            .AppendWithoutMessage(type, renamedByMember, isGeneric)
            .EndBlock()
            .EndBlockIf(hasNamespace);

        var hintNamespacePart = hasNamespace ? type.Namespace + "." : string.Empty;
        var hintName = $"{hintNamespacePart}{type.ContainingTypeChain}{type.TypeName}{aritySuffix}ProfilerMarkerExtensions.g.cs";
        context.AddSource(hintName, code.GetSourceText());
    }

    private static List<ImmutableArray<RenamedCall>> AssignUniqueFieldNames(ImmutableArray<ImmutableArray<MarkerCall>> memberGroups)
    {
        var seen = new Dictionary<string, int>();
        var result = new List<ImmutableArray<RenamedCall>>(memberGroups.Length);

        foreach (var member in memberGroups)
        {
            var renamed = ImmutableArray.CreateBuilder<RenamedCall>(member.Length);
            foreach (var call in member)
            {
                seen.TryGetValue(call.MarkerName, out var count);
                seen[call.MarkerName] = count + 1;
                var fieldName = count == 0 ? call.MarkerName : $"{call.MarkerName}_{count + 1}";
                renamed.Add(new RenamedCall(call, fieldName));
            }
            result.Add(renamed.MoveToImmutable());
        }

        return result;
    }

    private static CodeWriter AppendProfilerMarkers(
        this CodeWriter code,
        TypeData type,
        List<ImmutableArray<RenamedCall>> members,
        bool isGeneric)
    {
        if (isGeneric)
        {
            code.AppendLine($"private static class Markers{type.TypeParamList}{type.ConstraintsClause}")
                .BeginBlock();
        }

        var fieldVisibility = isGeneric ? "public" : "private";

        foreach (var member in members)
        {
            foreach (var renamed in member)
            {
                var markerValueExpression = BuildMarkerValueExpression(type, renamed.Call);
                code.AppendMultiline(
                    $"""
                    [{ProfilerMarkerGeneratedCode}]
                    {fieldVisibility} static readonly {ProfilerMarker} {renamed.FieldName} = new({markerValueExpression});

                    """);
            }
        }

        if (isGeneric)
            code.EndBlock().AppendLine();

        return code;
    }

    private static CodeWriter AppendWithoutMessage(
        this CodeWriter code,
        TypeData type,
        List<ImmutableArray<RenamedCall>> members,
        bool isGeneric)
    {
        code.AppendLine($"[{ProfilerMarkerGeneratedCode}]")
            .AppendLine($"public static {ProfilerMarker}.AutoScope Marker{type.TypeParamList}(this {type.FullyQualifiedDisplay} _, [{CallerLineNumberAttribute}] int line = -1){type.ConstraintsClause}")
            .BeginBlock()
            .AppendLine("#if ENABLE_PROFILER");

        var prefix = isGeneric ? $"Markers{type.TypeParamList}." : string.Empty;
        foreach (var member in members)
        {
            foreach (var renamed in member)
                code.AppendLine($"if (line is {renamed.Call.Line}) return {prefix}{renamed.FieldName}.Auto();");
        }

        code.AppendLine("#endif")
            .AppendLine("return default;")
            .EndBlock();

        return code;
    }

    private static string BuildMarkerValueExpression(TypeData type, MarkerCall call)
    {
        // call.Label may originate from a user-supplied .WithName("...") literal and can contain
        // quotes, backslashes or braces. Every literal fragment is emitted through ToLiteral so the
        // result is always valid C# — the raw label is never interpolated verbatim into the source.
        if (type.Arity == 0)
            return ToLiteral($"{type.TypeName}.{call.Label} ({call.Line})");

        // Generic enclosing type: the runtime label interpolates typeof(T).Name per closed
        // instantiation, so build it as a concatenation of escaped literals and typeof() expressions
        // instead of one interpolated string (which would break on braces inside the label).
        var typeofExpressions = string.Join(
            " + \", \" + ",
            ExtractTypeParamNames(type.TypeParamList).Select(p => $"typeof({p}).Name"));

        var prefix = ToLiteral($"{type.TypeName}<");
        var suffix = ToLiteral($">.{call.Label} ({call.Line})");
        return $"{prefix} + {typeofExpressions} + {suffix}";
    }

    // Renders an arbitrary string as a valid C# double-quoted string literal (quotes included),
    // escaping quotes, backslashes and control characters so user-supplied .WithName(...) text can
    // never produce malformed generated source.
    private static string ToLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var c in value)
        {
            switch (c)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\0': builder.Append("\\0"); break;
                case '\a': builder.Append("\\a"); break;
                case '\b': builder.Append("\\b"); break;
                case '\f': builder.Append("\\f"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case '\v': builder.Append("\\v"); break;
                default:
                    if (c < ' ')
                        builder.Append("\\u").Append(((int)c).ToString("x4"));
                    else
                        builder.Append(c);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static IEnumerable<string> ExtractTypeParamNames(string typeParamList)
    {
        if (string.IsNullOrEmpty(typeParamList)) yield break;

        var inner = typeParamList.Substring(1, typeParamList.Length - 2);
        foreach (var part in inner.Split(','))
            yield return part.Trim();
    }

    private readonly struct RenamedCall
    {
        public readonly MarkerCall Call;
        public readonly string FieldName;

        public RenamedCall(MarkerCall call, string fieldName)
        {
            Call = call;
            FieldName = fieldName;
        }
    }
}
